name: Build and Push Docker Image to GCP Artifact Registry

on:
  push:
    branches: [pro]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Extract artifact registry domain
        run: echo "ARTIFACT_DOMAIN=$(echo ${{ vars.ARTIFACT_REGISTRY }} | awk -F'/' '{print $1}')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Docker auth
        run: gcloud auth configure-docker ${{ env.ARTIFACT_DOMAIN }} --quiet

      - name: Extract repository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            --tag ${{ vars.ARTIFACT_REGISTRY }}/${{ env.REPO_NAME }}:${{ github.sha }} \
            --tag ${{ vars.ARTIFACT_REGISTRY }}/${{ env.REPO_NAME }}:latest \
            .

      - name: Push Docker image
        run: |
          docker push ${{ vars.ARTIFACT_REGISTRY }}/${{ env.REPO_NAME }}:${{ github.sha }}
          docker push ${{ vars.ARTIFACT_REGISTRY }}/${{ env.REPO_NAME }}:latest
